sonic-slave/Dockerfile
* removed new lines in line 15 and 29 to fix Dockerfile syntax
* fixes #4
=> sonic-slave/Dockerfile: fixing syntax

scripts/sonic_build_Dockerfile
=> Updated with http support for apt

build.sh
Reviewed-by: Qi Luo <qiluo@microsoft.com>
=> Updated: docker build options changed to disable cached layers

jenkins/common/sonic-utilities-build/Jenkinsfile
The files are in the stretch folder.
=> [jenkins]: Change the path of sonic-utilities dependencies

jenkins/common/sonic-utilities-build-pr/Jenkinsfile
=> [jenkins]: add sonic-utilities-build-pr JenkinsFile

jenkins/common/sonic-swss-common-build/Jenkinsfile
=> [jenkins]: Fix swss-common build artifacts path

jenkins/common/sonic-telemetry-build/Jenkinsfile
=> [jenkins]: Fix telemetry build artifacts path

jenkins/common/sonic-swss-common-build-pr/Jenkinsfile, jenkins/common/sonic-swss-common-build/Jenkinsfile, scripts/common/sonic-swss-common-build/build.sh, scripts/common/sonic-swss-common-build/test.sh
=> [jenkins]: Move script out of Jenkinsfile for re-use purpose

scripts/common/sonic-swss-common-build/build.sh, scripts/common/sonic-swss-common-build/test.sh
=> [scripts]: Move Redis installation from build to test

scripts/common/sonic-swss-common-build/test.sh
=> [script]: Expose test results to Jenkins

jenkins/vs/sonic-sairedis-build-pr/Jenkinsfile, jenkins/vs/sonic-sairedis-build/Jenkinsfile, scripts/vs/sonic-sairedis-build/build.sh
=> [sairedis]: Make Jenkinsfile DRY

jenkins/mellanox/buildimage-mlnx-201811-rpc/Jenkinsfile
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
=> [jenkins] Add Mellanox 201811-rpc Jenkins job

scripts/common/sonic-swss-common-build/test.sh
=> [test]: Add -e to bash to exit immediately when script fails

scripts/common/sonic-swss-common-build/build.sh
=> [script]: Add -e to bash to exit immediately when script fails

jenkins/vs/sonic-swss-build/Jenkinsfile
=> [jenkins]: Add Ansi color wrapper

jenkins/common/sonic-telemetry-build-pr/Jenkinsfile, jenkins/common/sonic-telemetry-build/Jenkinsfile, scripts/common/sonic-telemetry-build/build.sh
=> [jenkins]: Add sonic-telemetry build script

jenkins/vs/sonic-swss-build-pr/Jenkinsfile, jenkins/vs/sonic-swss-build/Jenkinsfile, scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile, scripts/vs/sonic-swss-build/test.sh
=> [test]: Use docker-sonic-vs as the base instead of docker-config-engine

jenkins/common/sonic-utilities-build-pr/Jenkinsfile, jenkins/common/sonic-utilities-build/Jenkinsfile
=> [jenkins]: Add lock in sonic-utilities

jenkins/common/dep-build/Jenkinsfile
=> Remove snmp from dep-build

jenkins/mellanox/buildimage-mlnx-bmtor-rpc/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-bmtor/Jenkinsfile, scripts/vs/buildimage-vs-image/test.sh
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
=> [mellanox] Add SONiC bmtor ONE/RPC jobs

jenkins/vs/buildimage-vs-image-201911/Jenkinsfile
Adding New Jenkin Build Project:
Target: vs
Branch:201911
=> Adding Jenkin Build for 201911 Branch for vs target

jenkins/common/dep-build/Jenkinsfile
Updated Libnl version to version 3.5
Added libsensors4-dev to packages to be cached.
=> [build-tools] Updating dep build with new libraries' version

jenkins/common/sonic-telemetry-build-pr/Jenkinsfile
=> Add sonic-mgmt to telemetry PR build.

scripts/common/sonic-utilities-build/test.sh, scripts/vs/sonic-swss-build/test.sh
=> [vs tests] Enable test retries by default using flaky

scripts/common/sonic-utilities-build/test.sh, scripts/vs/sonic-swss-build/test.sh
=> [vs tests] Clean-up docker images after vs tests are done using them

scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
=> [vs tests] Add checksums for orchagent

scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
=> [vs tests] Uninstall swss before installing it for dvs test runs

scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
=> [dvs tests] Enable debug output for dpkg install

scripts/vs/buildimage-vs-image/runtest.sh
Run announce route test case first in order to populate bgp route
singed-off-by: Tamer Ahmer <tamer.ahmed@microsoft.com>
=> [vs image] Run announce route test case

jenkins/common/sonic-mgmt-framework-build-pr/Jenkinsfile, jenkins/common/sonic-mgmt-framework-build/Jenkinsfile, scripts/common/sonic-mgmt-framework-build/build.sh
Add sonic-mgmt-framework build job
=> [jenkins]: Add sonic-mgmt-framework build job

jenkins/barefoot/buildimage-bf-201911/Jenkinsfile
Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>
=> [jenkins] Add Barefoot 201911 Jenkins job

jenkins/common/sonic-telemetry-build-pr/Jenkinsfile, scripts/common/sonic-telemetry-build/build.sh
=> Fix telemetry build issues

jenkins/common/dep-build/Jenkinsfile, jenkins/common/linux-kernel-build-pr/Jenkinsfile, jenkins/common/linux-kernel-build/Jenkinsfile, jenkins/mellanox/sonic-swss-build/Jenkinsfile, scripts/bldenv/sonic-slave/build.sh
ensure the script to fail when any of the step in script fails
=> [jenkins]: add -e for all bash script

jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile, jenkins/vs/buildimage-vs-image-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-test/Jenkinsfile, jenkins/vs/buildimage-vs-image/Jenkinsfile, scripts/vs/buildimage-vs-image/runtest.sh
Signed-off-by: Guohan Lu <lguohan@gmail.com>
=> [jenkins]: analyze all test reports for sonic-mgmt pytests

jenkins/vs/sonic-sairedis-build-pr/Jenkinsfile
Signed-off-by: Guohan Lu <lguohan@gmail.com>
=> [sairedis-pr]: add color support in xterm

jenkins/common/linux-kernel-build/Jenkinsfile, jenkins/common/linux-kernel-buster-build-pr/Jenkinsfile
Signed-off-by: Guohan Lu <lguohan@gmail.com>
=> [kernel]: add pr for buster kernel build

jenkins/vs/buildimage-vs-image/Jenkinsfile
Signed-off-by: Guohan Lu <lguohan@gmail.com>
depends on https://github.com/Azure/sonic-buildimage/pull/4481
=> [jenkins]: build sonic-vs.vhdx image

jenkins/centec/buildimage-centec-all/Jenkinsfile
make sonic-centec.bin and sonic-centec-dbg.bin
=> add centec support

jenkins/broadcom/buildimage-brcm-201904/Jenkinsfile, jenkins/broadcom/buildimage-brcm-all-pr/Jenkinsfile, jenkins/broadcom/buildimage-brcm-all-released-pr/Jenkinsfile, jenkins/broadcom/buildimage-brcm-all/Jenkinsfile, jenkins/broadcom/buildimage-brcm-buster/Jenkinsfile
It will generate a self-signed certificate to sign the SWI image, the file size will increase 8K. It can be installed on the arista device which does even not support secure boot.
=> Sign Aboot swi image with oneshot generated test CA and certificates

jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile, jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
=> [mgmt] Move sonic-mgmt tests to the correct test runners

jenkins/common/sonic-utilities-build-pr/Jenkinsfile, jenkins/common/sonic-utilities-build/Jenkinsfile, scripts/common/sonic-utilities-build/build.sh
Dependency install test: https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/jenkins_testing/job/utilities-test/2/console
```
00:03:28.087  + sudo pip install buildimage/target/python-wheels/sonic_yang_mgmt-1.0-py2-none-any.whl
00:03:28.087  Processing ./buildimage/target/python-wheels/sonic_yang_mgmt-1.0-py2-none-any.whl
00:03:28.347  Installing collected packages: sonic-yang-mgmt
```
=> [utilities] Install SONiC YANG dependency for CLI tests

scripts/common/sonic-utilities-build/build.sh
=> [utilities] Add missing YANG dependencies for sonic-utilities tests

jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile, jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile, jenkins/vs/buildimage-vs-image-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-test/Jenkinsfile, jenkins/vs/buildimage-vs-image/Jenkinsfile, scripts/vs/buildimage-vs-image/test.sh
Adding this step to help investigate why all the BGP sessions are spontaneously resetting during some of the test runs.
=> [kvm] Dump PTF state to docker image after test failure

jenkins/marvell/buildimage-mrvl-201911-rpc/Jenkinsfile, jenkins/marvell/buildimage-mrvl-201911/Jenkinsfile, jenkins/marvell/buildimage-mrvl-all-rpc/Jenkinsfile, jenkins/marvell/buildimage-mrvl-all/Jenkinsfile
Add Marvell Intel SONIC Image Build Jobs for 201911 and master branch
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> [Jenkins] [Marvell] Add Marvell Intel SONIC Image Build Jobs for 201911 and master

jenkins/barefoot/buildimage-bf-202006/Jenkinsfile
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>
=> [barefoot] 202006 pipeline

jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile, jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile, jenkins/vs/buildimage-vs-image-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-test/Jenkinsfile, jenkins/vs/buildimage-vs-image/Jenkinsfile, scripts/vs/buildimage-vs-image/runtest.sh, scripts/vs/buildimage-vs-image/test.sh
Reverts Azure/sonic-build-tools#139
=> Revert "[kvm] Use run_tests.sh script in sonic-mgmt to run PR tests"

jenkins/vs/sonic-sairedis-build-pr/Jenkinsfile, jenkins/vs/sonic-sairedis-build/Jenkinsfile, scripts/vs/sonic-sairedis-build/build.sh, scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile, scripts/vs/sonic-sairedis-build/docker_build_script.sh
Adds the VS tests to the sairedis repo to catch regressions and build-breaks due to sairedis changes.
=> [sairedis] Add VS tests to sairedis repo

jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile, jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile, jenkins/vs/buildimage-vs-image-pr/Jenkinsfile, jenkins/vs/buildimage-vs-image/Jenkinsfile, scripts/vs/buildimage-vs-image/runtest.sh
=> [kvm] Fix KVM results archival

jenkins/barefoot/buildimage-bf-all/Jenkinsfile, jenkins/broadcom/buildimage-brcm-201811/Jenkinsfile, jenkins/broadcom/buildimage-brcm-201911/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-201911-t0/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-rpc-all/Jenkinsfile
Migrate 5 Jenkins job to pipeline job
=> Add 5 pipeline file, refer PR #173

jenkins/innovium/buildimage-invm-202006-rpc/Jenkinsfile, jenkins/innovium/buildimage-invm-202006/Jenkinsfile
Add Innovium platform jenkins build support for Sonic 202006
=> Add Innovium 202006 jenkins build support

jenkins/vs/buildimage-multiasic-vs-image-201911/Jenkinsfile
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
Adding a new Jenkins Job to build multi-asic VS image to bring up multi-asic VS for hwsku: msft_multi_asic_vs with 6 asics.
This job will create a sonic-vs.img.gz with asic.conf updated with NUM_ASIC=6.
=> Add new Jenkins job to build multiasic vs image from 201911 branch.

jenkins/common/sonic-wpa-supplicant-build-pr/Jenkinsfile, jenkins/common/sonic-wpa-supplicant-build/Jenkinsfile, scripts/common/sonic-wpa-supplicant-build/build.sh
This PR depends on https://github.com/Azure/sonic-wpa-supplicant/pull/18, please wait for this PR merged.
Signed-off-by: Ze Gan <ganze718@gmail.com>
=> Add wpa supplicant build tool

jenkins/common/sonic-wpa-supplicant-build-pr/Jenkinsfile, jenkins/common/sonic-wpa-supplicant-build/Jenkinsfile, scripts/common/sonic-wpa-supplicant-build/build.sh
Fix this PR: https://github.com/Azure/sonic-build-tools/pull/193
=> [wpa_supplicant]Fix wrong path

jenkins/centec-arm64/buildimage-centec-arm64-all/Jenkinsfile
Add Centec ARM64 build job to jenkins.
=> [centec-arm64-build]Add Centec ARM64 build tool

jenkins/barefoot/buildimage-bf-202012/Jenkinsfile, jenkins/broadcom/buildimage-brcm-202012/Jenkinsfile, jenkins/centec-arm64/buildimage-centec-arm64-202012/Jenkinsfile, jenkins/centec/buildimage-centec-202012/Jenkinsfile, jenkins/innovium/buildimage-invm-202012-rpc/Jenkinsfile, jenkins/innovium/buildimage-invm-202012/Jenkinsfile, jenkins/marvell-armhf/buildimage-mrvl-armhf-202012/Jenkinsfile, jenkins/marvell/buildimage-mrvl-202012-rpc/Jenkinsfile, jenkins/marvell/buildimage-mrvl-202012/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-202012-rpc/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-202012/Jenkinsfile, jenkins/nephos/buildimage-nps-202012/Jenkinsfile, jenkins/vs/buildimage-vs-image-202012/Jenkinsfile
=> [202012] Add pipelines for all 202012 image builds

scripts/vs/sonic-sairedis-build/build.sh
=> [vs] Fix sairedis vs build

jenkins/broadcom/buildimage-brcm-202012/Jenkinsfile, jenkins/innovium/buildimage-invm-202012/Jenkinsfile, jenkins/marvell/buildimage-mrvl-202012/Jenkinsfile, jenkins/mellanox/buildimage-mlnx-202012/Jenkinsfile, jenkins/nephos/buildimage-nps-202012/Jenkinsfile, jenkins/vs/buildimage-vs-image-202012/Jenkinsfile
=> [202012] Add debug packages to 202012 builds

jenkins/common/dep-build/Jenkinsfile
Change the dep-build branch, where the ixgbe target is still available
=> Change the dep-build branch, where the ixgbe target is still available

jenkins/mellanox/buildimage-mlnx-cache/Jenkinsfile
- Copy the original file from Xuhui's branch
- Disable ptf build
Signed-off-by: Ying Xie <ying.xie@microsoft.com>
=> [mlnx cache build] copy mellanox cache build file from Xuhui's branch

jenkins/mellanox/buildimage-mlnx-cache/Jenkinsfile
Signed-off-by: Ying Xie <ying.xie@microsoft.com>
=> [mlnx cache build] build docker-syncd-mlnx-rpc.gz

jenkins/common/sonic-utilities-build-pr/Jenkinsfile, scripts/common/sonic-utilities-build/build_201811.sh
Support 201811 branch PR check builds by using new 201811 build script
=> [sonic-utilities] Support PR check builds for 201811 branch

jenkins/vs/buildimage-multiasic-vs-image-201911/Jenkinsfile
[multi-asic]: Fix the string to be updated in asic.conf
with escape character without which the quotes were
not interpreted correctly.
Removing renaming of the final target file.
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
=> [multi-asic]: Fix the string to be updated in asic.conf

jenkins/vs/buildimage-multiasic-vs-image-201911/Jenkinsfile
[multi-asic]: Update asic.conf string to remove escape sequence.
asic.conf does not get updated with right multi-line string,
so split the string to multiple statement to avoid
using escape characters.
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
=> [multi-asic]: Update asic.conf string to remove escape sequence.
