Azure/sonic-build-tools

- sonic-slave/Dockerfile
The build process still requires squashfs-tools and zip to be installed in the Docker build environment.
Otherwise I see messages like:
mksquashfs: command not found  etc. pop up and the build fails.
The last commit removed the installation of these tools in the Dockerfile and this commit brings them back in.
> Dockerfile changes broke Sonic build

- config/sonic-nas.sources.list
Need to remove the 10. address as it is no longer useful and negatively impacts the build.
> Removing reference to a no longer useful IP

- sonic-slave/Dockerfile
It is used during build process, not required in runtime.
> Install python3-pip for build py3 wheels

- jenkins/common/sonic-utilities-build/Jenkinsfile
```
+ git clone https://github.com/Azure/sonic-swss
fatal: destination path 'sonic-swss' already exists and is not an empty directory.
```
> [jenkins]: Resolve folder name conflicts in sonic-utilities-build

- jenkins/common/dep-build/Jenkinsfile
lldpd depends on libsnmp, since we removed snmp from this job, we also need remove lldpd
> Remove lldpd from dep-build

- scripts/common/sonic-utilities-build/build.sh
During sonic-utilities builds on Jenkins, the unit tests in the sonic-utilities-tests directory of the sonic-utilities repo were failing with errors like,
```
AttributeError: 'Result' object has no attribute 'stdout'
```
This was because 'stdout' and 'stderr' were not added as members of the Result structure in the Python Click library until version 7.0. The slave container may contain an older version if installed via a .deb package, as it is the latest version available from Debian. However, since we need version 7.0 to run these tests, this patch will remove the Debian package and force an installation of Click >= 7.0 via pip.
> [Jenkins] Install Click version >= 7.0 to fix sonic-utilities unit tests during build

- scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
> [sonic-swss-build] Check md5 hash for swss deb package

- scripts/common/sonic-swss-common-build/test.sh
redis-server starts once installation finishes here `sudo dpkg -i buildimage/target/debs/stretch/redis-server_*.deb` , so restarting redis-server is needed to involve redis.conf update.
> Restart redis-server to load changes in redis.conf

- jenkins/vs/buildimage-vs-image-test/Jenkinsfile
- scripts/vs/buildimage-vs-image/runtest.sh
With multiple test suites running in succession, the tr.xml get overwritten
with last test suite that run. With this change, every test suite will
produce its test report. Also, changing JUnit post API to pick up all
test reports generated.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
> [vs image] Add support for multiple test reports

- scripts/vs/buildimage-vs-image/runtest.sh
BGP speaker test was taken out by commit 4365219c due to both test case and platform instabilities. PR https://github.com/Azure/sonic-mgmt/pull/1384 addressed platform issues and PR https://github.com/Azure/sonic-mgmt/pull/1387 addresses speaker test issues. Once the latter PR is pushed in, this PR will put back BGP speaker test.
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
> [build] Adding back BGP speaker test

- jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
Changing JUnit post API to pick up all test reports generated. A change was done earlier to generate multiple test reports in pr #79 
signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
> [vs image] Add support for multiple test reports to buildimage-vs jobs

- scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
Removing the -D10 and some of the md5sums as we've finished investigating this issue. Leaving in the orchagent md5sum as an FYI, could also be useful for monitoring in the near-future.
> [swss build] Remove verbose debug logs from swss build

- jenkins/barefoot/buildimage-bf-201904/Jenkinsfile
- jenkins/barefoot/buildimage-bf-201911/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-201904/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-all/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-buster/Jenkinsfile
- jenkins/generic/buildimage-baseimage/Jenkinsfile
- jenkins/innovium/buildimage-invm-201811-rpc/Jenkinsfile
- jenkins/innovium/buildimage-invm-201811/Jenkinsfile
- jenkins/innovium/buildimage-invm-201911-rpc/Jenkinsfile
- jenkins/innovium/buildimage-invm-201911/Jenkinsfile
- jenkins/innovium/buildimage-invm-all-rpc/Jenkinsfile
- jenkins/innovium/buildimage-invm-all/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-201811-rpc/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-201811/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-201904/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-201911-rpc/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-201911/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-all-pr/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-all-rpc/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-all/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-bmtor-rpc/Jenkinsfile
- jenkins/mellanox/buildimage-mlnx-bmtor/Jenkinsfile
- jenkins/nephos/buildimage-nps-201811/Jenkinsfile
- jenkins/nephos/buildimage-nps-201911/Jenkinsfile
- jenkins/nephos/buildimage-nps-all/Jenkinsfile
- jenkins/vs/buildimage-vs-all/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201904/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201911/Jenkinsfile
- jenkins/vs/buildimage-vs-image-buster/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
SONiC build system inserts a branch name into image version string.
However, jenkins checkouts from the branch, so HEAD is in detached
state, in this case, "git rev-parse --abrrev-ref HEAD" returns HEAD.
This diff adds "LocalBranch" to extenstions, so jenkins will checkout
and create a local branch named as remote branch, this should fix the
issue with image version string.
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>
> Add LocalBranch to extentions in checkout step.

- README.md
Verified that the updated link works.
> Fix URL to SONiC Jenkins build link

- jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
- scripts/mgmt/test.sh
Description: This job runs KVM tests against the latest sonic-mgmt master branch. It is intended to measure the stability of the sonic-mgmt master branch. It also doesn't require a full rebuild of the sonic image, which should let us run the tests more often than buildimage-vs-image.
> [mgmt] Add canary KVM tests for sonic-mgmt repo

- jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
Description: This job runs KVM tests against PRs in the sonic-mgmt repo. It is intended to prevent breaking changes from being merged to the sonic-mgmt repo and blocking progress in sonic-mgmt and sonic-buildimage.
> [mgmt] Add PR test for sonic-mgmt repo

- jenkins/mellanox/buildimage-mlnx-all-rpc/Jenkinsfile
So future PR build could read from the cache if already build on master branch.
> Enable wcache for buildimage-mlnx-all-rpc build job

- jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
- jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-all/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image-buster/Jenkinsfile
- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
there will be three roles of workers
- jenkins-build-workers
- jenkins-vstest-workers
- jenkins-kvmtest-workers
The build workers are mainly for build the image.
The vstest workers are mainly for swss/sonic-utilities vs tests
The kvmtest workers are manly for sonic-mgmt kvm tests
The vstest and kvmtest can share the same physical servers. However, to help debug, we introduce two roles so that they can be separated to avoid their jobs affecting each other.
> move build job to build worker and kvm test to kvmtest workers

- scripts/mgmt/test.sh
Fix the sonic-mgmt PR testing no test result issue.
The sonic-mgmt PR testings has no test results after #115 was merged. The `scripts\vs\buildimage-vs-image\runtest.sh` file now needs to get tbname from argument. 
**Fix:**
To fix this issue, I supplied `vms-kvm-t0` argument while calling this runtest.sh script in `scripts\mgmt\test.sh`.
> [mgmt] Fix sonic-mgmt pr test no result issue

- jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
- jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
This is a temporary fix while we work on resolving https://github.com/Azure/sonic-buildimage/issues/4822. There are certain improvements we need to make (like dumping the KVM state if the tests timeout), but this is still an improvement over waiting for someone to notice the tests are stuck before freeing up the workers.
> [kvm] Add timeout for KVM tests

- scripts/common/sonic-utilities-build/build.sh
Add jsondiff PKG, needed for tests.
Not getting installed by specifying in the setup.py.
```
[12:11 AM] Praveen Chaudhary
00:09:22  running pytest 00:09:22  00:09:22  Note: Bypassing https://pypi.org/simple/jsondiff/ (disallowed host; see http://bit.ly/2hrImnY for details). 00:09:22  00:09:22  Couldn't find index page for 'jsondiff' (maybe misspelled?) 00:09:22  00:09:22  Note: Bypassing https://pypi.org/simple/ (disallowed host; see http://bit.ly/2hrImnY for details). 00:09:22  00:09:22  No local packages or working download links found for jsondiff==1.2.0 00:09:22  Searching for jsondiff==1.2.0
```
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
> [sonic-utilities-build/build.sh]: Add jsondiff PKG.

- jenkins/common/sonic-mgmt-common-build-pr/Jenkinsfile
- jenkins/common/sonic-mgmt-common-build/Jenkinsfile
- scripts/common/sonic-mgmt-common-build/build.sh
- scripts/common/sonic-mgmt-common-build/test.sh
- scripts/common/sonic-mgmt-framework-build/build.sh
- scripts/common/sonic-mgmt-framework-build/test.sh
- scripts/common/sonic-telemetry-build/build.sh
1) Added jenkinsfile, build and test scripts for sanity checking of
sonic-mgmt-common PRs. Test stage runs cvl and translib go test cases.
Also added periodic sanity for latest sonic-mgmt-common code.
2) Modified sonic-mgmt-framework PR & sceduled sanities to download and
build latest sonic-mgmt-common fist. Cleaned up build script to include
only sonic-mgmt-framework related stuffs. Translib, cvl specific steps
are moved to sonic-mgmt-common's build script.
3) Introduced a test stage for sonic-mgmt-framework sanity. It runs REST
server go test cases.
4) Modified sonic-telemetry build script to clone and build
sonic-mgmt-common first. Removed dependency on sonic-mgmt-framework.
Signed-off-by: Sachin Holla <sachin.holla@broadcom.com>
> Build scripts for sonic-mgmt-common

- jenkins/common/sonic-mgmt-common-build-pr/Jenkinsfile
- jenkins/common/sonic-mgmt-framework-build-pr/Jenkinsfile
- jenkins/common/sonic-mgmt-framework-build/Jenkinsfile
- jenkins/common/sonic-telemetry-build-pr/Jenkinsfile
- jenkins/common/sonic-telemetry-build/Jenkinsfile
- scripts/common/sonic-mgmt-framework-build/build.sh
- scripts/common/sonic-mgmt-framework-build/test.sh
- scripts/common/sonic-telemetry-build/build.sh
1\) Use buildimage-vs-image artifacts for sonic-mgmt-framework builds.
It requires buster packages.
2\) Changed telemetry build script to install redis directly through apt.
3\) Changed mgmt-framework to make it similar to telemetry build script's
layout -- install deps and compile sonic-mgmt-common by itself, without
depending on sonic-mgmt-common's build script.
> Telemetry and mgmt-framework build fixes

- scripts/common/sonic-swss-common-build/test.sh
A unit test for sonic-swss-common tests a function that connects to Redis via Unix socket. This PR enables Unix socket for sonic-swss-common tests.
> Enable Redis Unix socket for swss-common tests

- scripts/common/sonic-utilities-build/build.sh
This is an addendum to PR https://github.com/Azure/sonic-build-tools/pull/132, which didn't fully transition the build environment to Buster.
> [sonic-utilities-build] Complete the transition to build in Buster environment

- scripts/common/sonic-utilities-build/build.sh
Buster slave container in Docker repo has `-johnar` suffix, whereas Stretch didn't.
> [sonic-utilities-build] Adjust name of Buster slave container

- jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
- jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
- scripts/vs/buildimage-vs-image/runtest.sh
- scripts/vs/buildimage-vs-image/test.sh
Uses the `run_test.sh` script from `sonic-mgmt` to run the pytests to catch regressions in `run_test.sh` during PR testing. Next step is to use the "device_type=vs" marker or something similar to run the tests rather than using a hard-coded list.
> [kvm] Use run_tests.sh script in sonic-mgmt to run PR tests

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- jenkins/common/sonic-utilities-build/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
Install and archive both Python 2 and Python 3 packages to prepare for eventual transition of sonic-utilities to Python 3.
> [sonic-utilitites-build] Install sonic-py-common and archive artifacts

- scripts/common/sonic-utilities-build/build.sh
sonic-config-engine now depends on sonic-py-common. Install in the proper order.
> [sonic-utilitites-build] Install sonic_config_engine after sonic_py_common

- scripts/common/sonic-utilities-build/build.sh
sonic-py-common has other dependencies, so we also need to install Python 3 versions of those packages. Since we are not yet building a Python 3 version of sonic-utilities, I am temporarily omitting the installation of the Python 3 sonic-py-common package.
> [sonic-utilities-build] Do not install Python 3 version of sonic-py-common for now

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- jenkins/common/sonic-utilities-build/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
Currently the builds for `sonic-utilities` fetch and install the very latest versions of `swss-common`, `sairedis`, and `swss` to run the tests.
This is problematic because if ever any of those packages are out of sync (e.g. `swss-common` receives a new update and the other two have not been rebuilt in the interim to accommodate this new change), then the `utilities` tests will experience a bunch of odd errors/failures in a very short window of time. These are difficult to debug and they block the PR pipeline for hours at a time.
We could get around this by rebuilding all of the packages for the utilities build, but seeing as the `utilities` submodule can be updated and merged into the master `build-image` independently of the other three I …
> [utilities] Remove dependencies on latest swss and sairedis updates from utilities builds

- scripts/vs/buildimage-vs-image/runtest.sh
- scripts/vs/buildimage-vs-image/test.sh
https://github.com/Azure/sonic-mgmt/pull/2072 renames `veos.vtb` to `veos_vtb` to allow Ansible to use the YAML inventory parser to parse the file. This patch updates VS scripts to refer to the new file name.
> [vs] Rename 'veos.vtb' to 'veos_vtb'

- scripts/vs/sonic-sairedis-build/build.sh
- scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile
sairedis and swss are compiled with the latest swsscommon, but the swsscommon debian is not installed in the container. This can cause symbol table mismatch failures as seen here:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-sairedis-build/1175/
This fixes that bug by installing the swsscommon used for the build into the docker-sonic-vs container.
> [sairedis] Fix sairedis test setup

- jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
- jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
- scripts/vs/buildimage-vs-image/runtest.sh
- scripts/vs/buildimage-vs-image/test.sh
We want to use `run_tests.sh` to run KVM tests in order to prevent regressions in that script in sonic-mgmt.
Previously we tried this and had to revert since the tests were finishing all the way through even when errors occurred, making it difficult to debug. Now we have added the `-q 1` option to replicate the old behavior of exiting after the first error.
> [kvm] Use run_tests.sh script to run KVM tests

- jenkins/vs/buildimage-vs-image-test/Jenkinsfile
`buildimage-vs-image-test` was overlooked by #150. This PR brings the result archival up to date with #149.
> [kvm] Fix log output for buildimage-vs-image-test job

- jenkins/vs/sonic-swss-build-pr/Jenkinsfile
- jenkins/vs/sonic-swss-build/Jenkinsfile
- scripts/vs/sonic-swss-build/build.sh
Fixes Azure/sonic-swss#1404
The addition of `sonic-sairedis` VS testing (https://github.com/Azure/sonic-build-tools/pull/133) led to `swss_1.0.0_amd64.deb` being added to the list of `sairedis` artifacts. Because of this change, the artifacts from `sairedis`, which is based on the latest `swss`, were overwriting the PR-built `swss` package.
This change narrows the list of artifacts being copied for the DVS build so that this does not happen again in the future. It also moves the swss install to the end.
> [vs] Fix issue of swss debian being overwritten by sairedis

- scripts/vs/sonic-sairedis-build/build.sh
- scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile
- scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
While testing https://github.com/Azure/sonic-swss-common/pull/376 we found that the warm reboot VS tests were failing.
Judy investigated further and found a bunch of errors like this:
```
Aug 18 20:25:23.337191 e77f483613a6 INFO #supervisord: restore_neighbors return importlib.import_module('_swsscommon')
Aug 18 20:25:23.337254 e77f483613a6 INFO #supervisord: restore_neighbors   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Aug 18 20:25:23.337283 e77f483613a6 INFO #supervisord: restore_neighbors     __import__(name)
Aug 18 20:25:23.337309 e77f483613a6 INFO #supervisord: restore_neighbors ImportError: No module named _swsscommon
```
So we looked deeper and noticed that swsscommon is installed in the VS container, …
> [vs] Install python-swsscommon inside the DVS image

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- jenkins/common/sonic-utilities-build/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
Reverts Azure/sonic-build-tools#146
When we made this change we did not account for changes in swss leading to changes in the test behavior. This is causing failures like the ones seen here:
https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-utilities-build/1559/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-utilities-build-pr/2209/
In order to de-couple the `utilities` and `swss` builds, we need to be able to associate the tests w/ the orchagent version. This will take some time to research and implement, so I'm reverting this PR for now to un-block sonic-utilities.
> Revert "[utilities] Remove dependencies on latest swss and sairedis updates from utilities builds"

- scripts/vs/buildimage-vs-image/runtest.sh
This test has become extremely flaky after a recent SWSS submodule update. It's not super clear where the problem lies, so we're going to disable this test for now and open an issue to track the image and/or test fix so that it can be added back quickly.
https://github.com/Azure/sonic-buildimage/issues/5273
> [kvm] Disable LAG update test for KVM

- jenkins/broadcom/buildimage-brcm-all-pr/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-all-released-pr/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-all/Jenkinsfile
- jenkins/broadcom/buildimage-brcm-buster/Jenkinsfile
Reverts Azure/sonic-build-tools#140
This commit modified `jenkins/broadcom/buildimage-brcm-all-released-pr/Jenkinsfile`, and if a buildimage PR targeting 201811 branch, that  job will fail because the file `convert-pfx-cert-format.sh` does not exists on https://github.com/Azure/sonic-buildimage/tree/201811 branch.
We need to revisit this commit and make it general to all branches.
> Revert "Support to use the same certificate to sign image"

- scripts/vs/buildimage-vs-image/runtest.sh
Test make sure cleanup happens of Port-channel Kernel devices.
This test case track the fixes done by PR:
Azure/sonic-swss#1407
Azure/sonic-swss#1159
Verified on 201911 KVM Image test case is passed
johnar@6b57928a7072:/data/Networking-acs-sonic-mgmt/tests$ !252
sudo py.test --inventory "veos.vtb" --host-pattern vlab-01 --module-path "../ansible/library/" --testbed vms-kvm-t0 --testbed_file "vtestbed.csv"  -vvv pc/test_po_cleanup.py --skip_sanity
=============================================================================================== test session starts ===============================================================================================
platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
ansible: 2.8.7 …
> Added the test case for Port Channel cleanup into runtest.sh

- scripts/vs/sonic-sairedis-build/docker_build_script.sh
Required for sonic-sairedis compilaton, since new communication channel was added between syncd/sairedis using libzmq
> Install libzmq in sonic-sairedis-build

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- jenkins/common/sonic-utilities-build/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
Build sonic-utilities as a Python wheel instead of a Debian package to support https://github.com/Azure/sonic-utilities/pull/1122
> [sonic-utilities] Build as Python wheel instead of Debian package

- scripts/vs/sonic-sairedis-build/docker_build_script.sh
Since libzmq does not use actual shared memory to communicate between processes, we will implement shared memory model on single cpu by our own using libboost in sonic-sairedis repo
> Add libboost for sonic-sairedis-script

- scripts/common/sonic-utilities-build/build.sh
When we were building the sonic-utilities package as a Debian package, the `python setup.py --command-packages=stdeb.commandbdist_deb` operation would automatically run the unit tests before build. Now that we've changed to building a Python wheel, the `python setup.py bdist_wheel` operation does not automatically run the unit tests.
In this patch, we explictly run the unit tests using `sudo python setup.py test` before building the wheel.
> [sonic-utilities] Explicitly run unit tests in build script

- scripts/common/sonic-utilities-build/build.sh
Now that sonic-utilities is built as a wheel, the target/python-debs/ directory of the VS build is empty and therefore does not get archived which caused the `mount` command to fail.
Also no longer install click-default-group, as sonic-utilities no longer depends on it.
> [sonic-utilities] No longer mount target/python-debs/ directory

- scripts/common/sonic-utilities-build/build.sh
In PR https://github.com/Azure/sonic-build-tools/pull/167, we no longer mount the target/python-debs/ directory as it doesn't get archived now that it's empty. We also shouldn't try to unmount the directory.
> [sonic-utilities] Don't umount target/python-debs/ directory, as it's no longer mounted

- jenkins/vs/sonic-swss-build-pr/Jenkinsfile
- jenkins/vs/sonic-swss-build/Jenkinsfile
- scripts/vs/sonic-swss-build/build.sh
The sonic-utilities build no longer creates a `.deb` package, so the reference needs to be updated in `swss`. Since this package isn't currently used anywhere in `swss`, I have removed it altogether.
> [swss] Remove references to deprecated sonic-utilites debian package

- scripts/common/sonic-mgmt-common-build/test.sh
- scripts/common/sonic-mgmt-framework-build/test.sh
Multi db enhancements in sonic-mgmt-common requires database_config.json
file for running tests. Updated mgmt-common and mgmt-framework PR test
runner scripts to setup the a dummy database_config.json file.
It includes only 1 local redis instance, running on standard port 6379.
> Configure db config file for mgmt-framework and mgmt-common PR tests

- scripts/common/sonic-utilities-build/build.sh
As sonic-utilities is now built as a wheel, setuptools/pip will install all external dependencies from PyPI at build or install time as specified in the setup.py file. Thus, we no longer need to explicitly install those packages.
> [sonic-utilities] No longer explicitly install external dependencies

- jenkins/common/python-asyncsnmp-build/Jenkinsfile
- jenkins/common/python-swsssdk-build/Jenkinsfile
1. upstream job has changed name.
2. build log 10 is not enough when build continuously fail.
> Fix Jenkins pipeline file bugs

- scripts/common/sonic-utilities-build/build.sh
sonic-slave-buster behavior has changed recently due to modification of Python dependency installation such that `pip` now aliases to `pip3`, which causes failures as `pip3` fails to install Python 2 packages. This patch explicitly calls `pip2` and `python2` to prevent this.
> [sonic-utilities] Explicitly call pip2 and python2

- jenkins/broadcom/buildimage-brcm-all/Jenkinsfile
If this flag isn't set, then the SYNCD_RPC build variable never gets set (see: https://github.com/Azure/sonic-buildimage/blob/6088bd59ded064f392b7618872e1306057b955e1/rules/syncd.mk#L15).
As a result, syncd never gets added to the list of deps for the syncd-rpc docker here: https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/docker-syncd-brcm-rpc.mk
Because of this, the syncd-rpc docker that is currently being built on Jenkins is missing syncd entirely, causing it to crash during startup because it can't find/run any of the syncd binaries.
> [brcm] Add ENABLE_SYNCD_RPC flag for BRCM syncd-rpc build

- scripts/common/sonic-utilities-build/build.sh
sonic-utilities will depend on sonic-swss-common
> [sonic-utilities] Install swsscommon deb packages before unit test

- scripts/common/sonic-utilities-build/build.sh
In preparation for moving sonic-utilities to Python 3, in the sonic-utilities build script, we install all the Python 3 dependencies and attempt to test and build the Python 3 version of the package. This will ensure we can see the Python 3 build/test success status in the PR check build output. However, we will not fail the build job yet if the Python 3 test or build fails.
> [sonic-utilities] Test and build Python 3 package, but don't fail build yet

- scripts/common/sonic-utilities-build/build.sh
Only test and build Python 3 package of sonic-utilities. Eliminate Python 2 build and do not install Python 2 dependencies.
https://github.com/Azure/sonic-utilities/pull/1128 is silently passing all Python 3 unit tests (see output [here](https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-utilities-build-pr/2980/consoleFull)). Once this PR is merged, then the check build will pass, allowing that PR to merge.
> [sonic-utilities] Only test and build Python 3 package

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
- scripts/common/sonic-utilities-build/build_201911.sh
If the target branch is "201911", we will copy artifacts from the latest buildimage-vs-201911 build, then build the sonic-utilities Python 2 Debian package. We will not run SwSS tests against the 201911 branch PR, only against the master branch.
> [sonic-utilities] Support PR check builds for 201911 branch

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
It appears that in declarative pipelines, conditional statements must be enclosed within `script` blocks, otherwise we will see errors like the following:
```
14:10:20  org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
14:10:20  WorkflowScript: 14: Expected a step @ line 14, column 17.
14:10:20                     if ('${ghprbTargetBranch}' == '201911') {
14:10:20                     ^
```
> [sonic-utilities] Enclose conditional statements in a 'script' block

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
Apparently, environment variables must be accessed from `env` in pipelines. Reference: https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables
> [sonic-utilities] Add 'env.' prefix to GHPRB environment variables

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- scripts/common/sonic-utilities-build/build_201911.sh
Remove quotes and `${}` from around environment variable in conditions. `${}` is only needed when referencing the variable in things like an `echo` statement.
Also, don't install packages which aren't relevant in 201911 branch
> [sonic-utilities] Remove quotes and ${} from around environment variable in conditions

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- 201911 branch does not have Pytest coverage support, so there are no coverage results to publish
- Also add 201911-branch-specific archiving logic
> [sonic-utilities-build-pr] Do not attempt to publish Pytest coverage for 201911 branch

- jenkins/marvell-armhf/buildimage-mrvl-armhf-all/Jenkinsfile
This commit adds Sonic Jenkins build support for platforms based on the Marvell
ARMv7 32-bit (armhf) SOC and a Marvell Datapath ASIC.
> [jenkins] Add Marvell ARMv7 armhf SOC support

- scripts/common/sonic-utilities-build/build_201911.sh
Something changed recently which caused the sonic-utilities 201911 PR build to fail to install the `mock` package from PyPI implicitly. Here, we install version 3.0.5 (the latest version available for Python 2) of the package explicitly before building the sonic-utilities package.
Also, explicitly call `pip2` and `python2` instead of `pip` and `python` just to ensure the proper versions are used.
> [sonic-utilities-build] Explicitly install 'mock' package and use Python 2 for 201911 branch

- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
We've started noticing strange errors when we try to checkout submodules during the Test stage of this Jenkins job, like this:
09:01:33  From https://github.com/Azure/sonic-telemetry
09:01:33     e54f9ca..d3336d1  master     -> origin/master
09:01:33  fatal: remote error: upload-pack: not our ref ca07e68bb8bafc6e5aab341c5c8a35605044a7d3
09:01:33  fatal: the remote end hung up unexpectedly
We've noticed these for sairedis and telemetry. The Build stage is working consistently, and the only difference we can see between this stage and the Test stage is this recursiveSubmodules flag. This PR sets that flag for the Test stage as well in order to mitigate the impact on our PR builds.
> [vs-image-pr] Fix submodule checkout for VS image tests

- jenkins/marvell-armhf/buildimage-mrvl-armhf-all/Jenkinsfile
This commit provides the following improvements to the Marvell armhf builds
performed by Jenkins.
1. Improve build performance by attempting a build using SONIC_BUILD_JOBS=4. If
that fails then try SONIC_BUILD_JOBS=2. If that fails then try
SONIC_BUILD_JOBS=1. If that fails we are done.
2. Disable concurrent builds from the same branch. This strives to avoid a
current armhf build limitation where multiple builds executed on the same
build machine interfere with each other.
> [jenkins] Marvell ARMv7 armhf build improvements

- jenkins/marvell-armhf/buildimage-mrvl-armhf-all/Jenkinsfile
This commit fixes a bug in the changes provided in PR# 201.
In particular the number of concurrent build jobs (SONIC_BUILD_JOBS) is
correctly specified.
> [jenkins] Marvell ARMv7 armhf build fix

- jenkins/marvell-armhf/buildimage-mrvl-armhf-all/Jenkinsfile
This commit addresses issues observed when building for Marvell
armhf. Specifically the following changes are being made.
1. Skip building the debug image for now so that the regular image can be made
available in a more timely manner.
2. Do not remove the generated sonic-slave docker image so that it can be
re-used by a subsequent build.
3. Add logic to cleanup the docker daemon avoiding potential interference with
a subsequent build.
4. Remove multi-arch build artifacts to avoid an out of disk space issue on
subsequent builds.
> [jenkins] Marvell armhf build improvements

- jenkins/common/sonic-swss-common-build-ubuntu/Dockerfile
Otherwise it may reuse cache
```
13:03:28  Step 1/10 : FROM ubuntu:bionic
13:03:28   ---> 2c047404e52d
13:03:28  Step 2/10 : RUN apt-get update
13:03:28   ---> Using cache
13:03:28   ---> cd848a921aa8
```
This cache may be outdated.
> Invalidate docker build cache when apt-get update

- jenkins/centec-arm64/buildimage-centec-arm64-202012/Jenkinsfile
- jenkins/centec-arm64/buildimage-centec-arm64-all/Jenkinsfile
Reference to PR #205, Optimize ARM64 build and make build more stable:
1. Skip building debug image
2. Add logic to cleanup the docker daemon
3. Remove all multi-arch build artifacts after building
> [Centec-ARM64]Reference to PR #205, Optimize ARM64 build

- jenkins/centec-arm64/buildimage-centec-arm64-202012/Jenkinsfile
- jenkins/centec-arm64/buildimage-centec-arm64-all/Jenkinsfile
- jenkins/marvell-armhf/buildimage-mrvl-armhf-202012/Jenkinsfile
- jenkins/marvell-armhf/buildimage-mrvl-armhf-all/Jenkinsfile
Add arm build lock to avoid concurrent arm build job on one Jenkins node.
> Add arm build lock to avoid parallel arm builds on one Jenkins node

- scripts/common/sonic-mgmt-common-build/build.sh
- scripts/common/sonic-mgmt-framework-build/build.sh
- scripts/common/sonic-telemetry-build/build.sh
Second version of libyang (v1.0.184) has been introduced recently.
Changed PR build scripts of sonic-mgmt-common, sonic-mgmt-framework and
sonic-telemetry repos to explicitly pick old libyang 1.0.73.
> Resolve libyang dependency for mgmt builds

- jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
- jenkins/vs/buildimage-vs-image/Jenkinsfile
Reverts Azure/sonic-build-tools#215
This commit exclude much more files than expected.
> Revert "Exclude some large files in archiveArtifacts"

- scripts/common/sonic-utilities-build/build.sh
since sonic-utilities requires  sonic_y_cable package for muxcable cli, sonic-platform-common install is required
for sonic-utilities build, for test cases to be passed in sonic-utilities. 
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>
> [sonic-utilities-build] add sonic-platform-common install for sonic-utilities build

- scripts/common/sonic-utilities-build/build.sh
Reverts Azure/sonic-build-tools#220
sonic-platform-common package is not currently built as part of the buildimage-vs-all build, so it is not available to install.
> Revert "[sonic-utilities-build] add sonic-platform-common install for sonic-utilities build"

- jenkins/common/sonic-utilities-build-pr/Jenkinsfile
- jenkins/common/sonic-utilities-build/Jenkinsfile
- scripts/common/sonic-utilities-build/build.sh
Recent changes to sonic-utilities requires importing sonic_y_cable package for muxcable cli. sonic_y_cable is part of the sonic-platform-common package, so we need to install sonic-platform-common before building sonic-utilities.
Also, change archiveArtifacts for master branch builds to archive Python 3 versions of the packages, as we no longer build a Python 2 sonic-utilities package.
> [sonic-utilities] Install sonic-platform-common package before build

- jenkins/vs/buildimage-multiasic-vs-image-201911/Jenkinsfile
Add change to include asic device IDs in asic.conf before building image.
Change number of asics to 4 as the test multi-asic vs image.
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
> [multi_asic]: Modify contents of asic.conf file to build image

- scripts/vs/sonic-swss-build/build_in_docker.sh
The swss build has started failing recently because it tries to install libsairedis, which complains that swsscommon is not installed. Changing the order should fix this issue.
> [vs] Fix dependency issue in swss build

- scripts/common/sonic-utilities-build/build_201911.sh
Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>
`pyroute2` was added to image in this PR https://github.com/Azure/sonic-buildimage/pull/6792
Install `pyroute2` in the sonic-utilities  PR  build script.
> [201911] install pyroute2

- scripts/common/sonic-utilities-build/build_201911.sh
This is to help https://github.com/Azure/sonic-utilities/pull/1547 pass build checker.
> Add deepdiff for sonic-utilities build preparation
